### ISSUE TITLE
Fazer plano de iterações

### ISSUE THREAD

**Issue by EnzEdu** [es20231/eqp2#13]
![Image](https://github.com/es20231/eqp2/assets/62819962/3e16ea8d-98af-4224-94ae-e2ea47cdf24d)

O que vocês acham deste plano de iterações? Coloquei espaços na etapa 3 para possíveis futuras implementações. Podemos fazer alterações futuramente também ao decorrer do trabalho.

**Comment by CiroMelo** [comment]
Achei deveras interessante meu grande amigo.
Sei que acabaste de de tornar o Scrum Master mas já conquistou meu voto para sua reeleição na terceira etapa haha

**Comment by GabrielAlves** [comment]
Pra mim está ótimo. Bastante conciso e organizado.

**Comment by JoaoMBarros** [comment]
Perfeito

**Comment by ingridm011** [comment]
Muito bom Enzo!
